# Base image
FROM node:10.16
# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY wait-for-it.sh package.json yarn.lock /usr/src/app/
RUN yarn install --production && yarn cache clean

# Bundle app source
COPY . /usr/src/app